### ISSUE TITLE
Be able o block a signal

### ISSUE THREAD

**Issue by iamsergio** [voidari/flutter_signals_slots#1]
Hello, thank you for this package, it's very useful!

It would be nice to be able to block/disable a signal temporarily. Similarly as can be done for Connection.

Here's a contrived made-up example of a real use case I have:

```dart
class Bag {
    List<Thing> _things;
    final sizeChanged = Signal();
       
    void removeOneThing(Thing t) {
        _things.remove(t);
        someImportantMethod();
        sizeChanged.emit();
    }
    
    void removeTwoThings(Thing t1, Thing t2) {
        sizeChanged.blocked = true; // blocking so unneeded signals aren't emitted
        removeOneThing(t1);
        removeOneThing(t2);
        sizeChanged.blocked = false;
        sizeChanged.emit();
    }
}
```

**Comment by graybrandonh** [comment]
Hey @iamsergio, I'm glad this package is useful! I believe what you are wanting makes sense. I will try to push a new version with your request in the next few hours. If not, I will get to it as soon as I can.

**Comment by iamsergio** [comment]
Thank you, it works!
