### ISSUE TITLE
declare signal with function signature?

### ISSUE THREAD

**Issue by naychrist** [voidari/flutter_signals_slots#3]
hi there, thanks for the package, surprisingly hard to find a good signals lib for dart!
have just implemented it to emit and receive a signal with a couple arguments. Just confirming there is no way to declare a signal using the intended function signature? e.g. `Signal<double,double> onDataChanged = Signal<double,double>();` instead of `Signal onDataChanged = Signal();`
thanks.

**Comment by graybrandonh** [comment]
Hey @naychrist, I'm glad you're finding it useful! I would love to add type support as you described and originally set out to do that, but I ran into some limitations with dart that prevented it.

When I have some time, I'll look into it again and let you know the exact reason, or make it typed if I missed something.

If you run into any problems or see something missing that you need, I'd be happy to troubleshoot or add support.

**Comment by graybrandonh** [comment]
@naychrist I'm not sure what problem I originally ran into, but I think I found a way to add types.

You'll have to declare it like:
Signal0 sig = Signal0()
Signal1< int> sig = Signal1< int>()
Signal2<int, double> sig = Signal2<int, double>()

I will need to do a lot more testing and finish the implementation, but it's passing my test cases.

I'll try to have something released by tonight (EST) or tomorrow morning if this proves to work.

**Comment by naychrist** [comment]
that would be fantastic :) hope it works out

**Comment by graybrandonh** [comment]
@naychrist Update this package to [1.1.0](https://github.com/voidari/flutter_signals_slots/releases/tag/v1.1.0) to use the new Signal type support. If you run into any issues, let me know.
